"""Local finance knowledge pack used for SFT seeds and assistant routing."""

from __future__ import annotations

import re


FINANCE_KNOWLEDGE = [
    {
        "term": "EBITDA",
        "aliases": ["ebitda"],
        "answer": "EBITDA stands for earnings before interest, taxes, depreciation, and amortization. It is often used as a rough operating profitability measure before capital structure, tax, and non-cash accounting effects.",
    },
    {
        "term": "Revenue",
        "aliases": ["revenue", "sales"],
        "answer": "Revenue is the total income a company earns from selling goods or services before subtracting expenses.",
    },
    {
        "term": "Operating Cash Flow",
        "aliases": ["operating cash flow", "cash flow from operating activities", "operating activities"],
        "answer": "Operating cash flow is the cash generated by a company's core business operations during a period.",
    },
    {
        "term": "Free Cash Flow",
        "aliases": ["free cash flow", "fcf"],
        "answer": "Free cash flow is the cash left after operating cash flow and capital expenditures. It helps show how much financial flexibility remains for debt reduction, reinvestment, or shareholder returns.",
    },
    {
        "term": "Gross Margin",
        "aliases": ["gross margin"],
        "answer": "Gross margin is the percentage of revenue left after subtracting the direct cost of goods or services sold.",
    },
    {
        "term": "Operating Margin",
        "aliases": ["operating margin"],
        "answer": "Operating margin measures operating income as a share of revenue and helps show how efficiently the core business is converting sales into profit.",
    },
    {
        "term": "Net Income",
        "aliases": ["net income", "net profit"],
        "answer": "Net income is profit after all operating costs, interest, taxes, and other expenses have been deducted from revenue.",
    },
    {
        "term": "EPS",
        "aliases": ["eps", "earnings per share"],
        "answer": "Earnings per share, or EPS, is the portion of profit attributable to each outstanding share of common stock.",
    },
    {
        "term": "CapEx",
        "aliases": ["capex", "capital expenditure", "capital expenditures"],
        "answer": "Capital expenditures are funds spent to acquire, maintain, or improve long-term assets such as property, equipment, or technology infrastructure.",
    },
    {
        "term": "10-K",
        "aliases": ["10-k", "10k", "annual report"],
        "answer": "A 10-K is an annual report filed with the SEC that describes a public company's business, risks, financial statements, and results.",
    },
    {
        "term": "Liquidity",
        "aliases": ["liquidity"],
        "answer": "Liquidity describes how easily a company can meet near-term obligations using cash or assets that can quickly be converted to cash.",
    },
    {
        "term": "Guidance",
        "aliases": ["guidance", "outlook"],
        "answer": "Guidance is management's forward-looking view of expected financial or operating performance for a future period.",
    },
]


QUESTION_PREFIX_RE = re.compile(
    r"^(?:what is|what does|define|explain|meaning of|tell me about)\s+",
    re.IGNORECASE,
)


def all_terms() -> list[dict]:
    return FINANCE_KNOWLEDGE


def lookup_finance_definition(question: str) -> dict | None:
    text = question.strip().lower().rstrip("?.! ")
    simplified = QUESTION_PREFIX_RE.sub("", text)
    for item in FINANCE_KNOWLEDGE:
        for alias in item["aliases"]:
            alias = alias.lower()
            if simplified == alias or text == alias or alias in simplified:
                return item
    return None
