"""Create a higher-quality instruction-style corpus for FinLLM SFT.

The output is still mostly grounded/extractive, but it uses multiple finance-
specific prompt types so the resulting model learns answer formats rather than
only generic continuation.
"""

from __future__ import annotations

import argparse
import json
import random
import re
from pathlib import Path

from tqdm import tqdm

from finllm.retrieval import chunk_text, normalize_text


SENTENCE_RE = re.compile(r"(?<=[.!?])\s+")
COMPANY_RE = re.compile(r"\b[A-Z][A-Za-z&.-]{2,}(?:\s+[A-Z][A-Za-z&.-]{2,}){0,2}\b")
NUMBER_RE = re.compile(r"\b(?:EUR|USD|\$|£)?\s?\d+(?:[\.,]\d+)?(?:\s?(?:million|billion|mn|m|bn|%))?\b", re.I)

CURATED_QA = [
    (
        "What is revenue?",
        "Revenue is the income a company earns from selling goods or services before deducting expenses. It represents the top line of an income statement and is a key indicator of business scale and market demand.",
    ),
    (
        "What is operating cash flow?",
        "Operating cash flow is cash generated by a company's core business operations. It measures the actual cash coming in from selling products or services, minus the cash going out for operating expenses. Unlike net income, it excludes non-cash items like depreciation and shows real liquidity from operations.",
    ),
    (
        "What is EBITDA?",
        "EBITDA means earnings before interest, taxes, depreciation, and amortization. It is a measure of operating performance that strips out financing decisions, tax environments, and accounting choices around asset depreciation. This makes it useful for comparing profitability across companies with different capital structures or tax situations.",
    ),
    (
        "What is a 10-K filing?",
        "A 10-K is an annual report filed with the SEC that describes a public company's business, risks, financial statements, and results. It is required for all publicly traded companies in the United States and provides comprehensive disclosure about operations, management, financial condition, and material risks. Investors use 10-Ks to perform fundamental analysis and due diligence.",
    ),
    (
        "Why can a financial language model hallucinate?",
        "A language model predicts likely text based on patterns learned during training, not from verified facts. This means it can generate plausible-sounding but incorrect numbers, company names, dates, or causal claims. Financial models are especially prone to hallucinating specific figures because they learn statistical patterns rather than retrieving actual data. All model outputs should be verified against retrieved evidence or primary sources before use in decision-making.",
    ),
    (
        "What does gross margin describe?",
        "Gross margin describes the share of revenue left after subtracting the direct cost of goods or services sold. It is calculated as (Revenue - Cost of Goods Sold) / Revenue, expressed as a percentage. A higher gross margin indicates better pricing power or lower production costs, which provides more room to cover operating expenses and generate profit.",
    ),
    (
        "Why is free cash flow important?",
        "Free cash flow shows how much cash remains after operating needs and capital investments. It is calculated as Operating Cash Flow minus Capital Expenditures. This metric matters because it represents the cash available for dividends, debt repayment, share buybacks, or strategic investments. Companies with strong free cash flow have more financial flexibility and are less dependent on external financing.",
    ),
    (
        "What is the difference between revenue and profit?",
        "Revenue is the total income from sales before any deductions, while profit is what remains after subtracting all expenses. Revenue shows business scale and market reach. Profit shows efficiency and sustainability. A company can have high revenue but low or negative profit if expenses are too high. Investors care about both: revenue for growth potential and profit for actual value creation.",
    ),
    (
        "What does it mean when a company has negative cash flow but positive earnings?",
        "This happens when accounting earnings include non-cash items or when cash is tied up in working capital. For example, a company might record revenue on credit (increasing earnings) but not yet collect the cash. Or it might be building inventory, which uses cash but doesn't reduce earnings until sold. Depreciation works the opposite way: it reduces earnings without using cash. Negative cash flow with positive earnings can be normal during growth phases, but sustained divergence is a red flag for quality of earnings.",
    ),
    (
        "Why do investors look at debt-to-equity ratio?",
        "The debt-to-equity ratio measures financial leverage by comparing total debt to shareholder equity. It shows how much a company relies on borrowed money versus owner investment. A higher ratio means more leverage, which amplifies both gains and losses. Too much debt increases bankruptcy risk, especially if cash flow weakens. Too little debt might mean the company is not using leverage to grow efficiently. The optimal ratio varies by industry: capital-intensive businesses typically carry more debt than software companies.",
    ),
    (
        "What is working capital and why does it matter?",
        "Working capital is current assets minus current liabilities. It represents the liquid resources available to fund day-to-day operations. Positive working capital means a company can cover short-term obligations. Negative working capital can signal liquidity problems, though some businesses (like retailers with fast inventory turnover) operate successfully with negative working capital. Changes in working capital affect cash flow: increasing inventory or receivables uses cash, while increasing payables preserves cash.",
    ),
    (
        "How do you interpret a P/E ratio?",
        "The price-to-earnings (P/E) ratio divides stock price by earnings per share. It shows how much investors are willing to pay for each dollar of earnings. A high P/E suggests investors expect strong future growth or that the stock is overvalued. A low P/E might indicate undervaluation or concerns about future performance. P/E ratios should be compared within the same industry, as growth companies typically have higher P/Es than mature businesses. A P/E of 15-25 is often considered reasonable for established companies, but context matters more than absolute numbers.",
    ),
    (
        "What is the purpose of depreciation in financial statements?",
        "Depreciation allocates the cost of long-term assets over their useful life rather than expensing the full cost upfront. This matches expenses with the revenue those assets help generate, following the matching principle in accounting. Depreciation is a non-cash expense: it reduces reported earnings but does not use cash. Different depreciation methods (straight-line, accelerated) affect the timing of expense recognition but not total cash spent. Understanding depreciation is crucial for analyzing cash flow versus accounting profit.",
    ),
    (
        "What does return on equity (ROE) measure?",
        "Return on equity measures how efficiently a company generates profit from shareholder investment. It is calculated as Net Income / Shareholder Equity. An ROE of 15-20% is generally considered strong, though this varies by industry. High ROE can indicate competitive advantage and efficient capital use, but it can also result from high leverage (debt increases ROE by reducing equity). Comparing ROE with return on assets (ROA) helps identify whether returns come from operational efficiency or financial leverage.",
    ),
    (
        "Why do companies buy back their own stock?",
        "Share buybacks reduce the number of outstanding shares, which increases earnings per share and can boost stock price. Companies buy back stock when they believe shares are undervalued or when they have excess cash but limited growth opportunities. Buybacks return value to shareholders without the tax implications of dividends. However, buybacks can be controversial if done at high prices or if the company should be investing in growth instead. The timing and price of buybacks significantly affect whether they create or destroy shareholder value.",
    ),
]


def split_sentences(text: str) -> list[str]:
    return [sentence.strip() for sentence in SENTENCE_RE.split(text) if sentence.strip()]


def first_sentences(text: str, *, max_sentences: int = 2, max_chars: int = 520) -> str:
    sentences = split_sentences(text)
    answer = " ".join(sentences[:max_sentences]) if sentences else text[:max_chars]
    answer = normalize_text(answer)
    if len(answer) > max_chars:
        answer = answer[: max_chars - 3].rstrip() + "..."
    return answer


def bullet_summary(text: str, *, max_points: int = 3) -> str:
    sentences = split_sentences(text)
    selected = [sentence for sentence in sentences if len(sentence) > 30][:max_points]
    if not selected:
        selected = [first_sentences(text)]
    return "\n".join(f"- {normalize_text(sentence)}" for sentence in selected)


def clean_chunk(text: str) -> str | None:
    text = normalize_text(text)
    if len(text) < 120:
        return None
    if text.count("<") > 2 or text.count(">") > 2:
        return None
    if "font-size" in text or "vertical-align" in text:
        return None
    if text.startswith("b'") or text.startswith('b"'):
        return None
    return text


def guess_company(text: str) -> str | None:
    matches = COMPANY_RE.findall(text)
    for match in matches:
        if match.lower() in {"the company", "the group", "net sales", "cash flow"}:
            continue
        return match
    return None


def has_keywords(text: str, *keywords: str) -> bool:
    lowered = text.lower()
    return any(keyword in lowered for keyword in keywords)


def has_numbers(text: str) -> bool:
    return bool(NUMBER_RE.search(text))


def format_example(instruction: str, answer: str, *, context: str | None = None) -> str:
    parts = ["<|user|>", instruction.strip()]
    if context:
        parts.extend(["", "Context:", context.strip()])
    parts.extend(["<|assistant|>", answer.strip(), "<|end|>"])
    return "\n".join(parts)


def records_for_chunk(chunk: str, rng: random.Random) -> list[dict]:
    records: list[dict] = []
    company = guess_company(chunk)
    summary_answer = bullet_summary(chunk)

    prompts = [
        (
            "Explain what this financial context means in clear terms.",
            summary_answer,
        ),
        (
            "Define the key financial concepts mentioned in this context.",
            first_sentences(chunk, max_sentences=3),
        ),
        (
            "Answer using only the provided financial context. Summarize the key facts.",
            summary_answer,
        ),
        (
            "Using only the provided context, write a concise financial summary.",
            first_sentences(chunk, max_sentences=3),
        ),
    ]

    targeted_prompts: list[tuple[str, str]] = []
    if has_keywords(chunk, "revenue", "sales"):
        targeted_prompts.extend([
            (
                "What does the context say about revenue or sales performance?",
                first_sentences(chunk, max_sentences=2),
            ),
            (
                "Explain the revenue trends described in this context.",
                first_sentences(chunk, max_sentences=2),
            ),
        ])

    if has_keywords(chunk, "cash flow", "operating activities", "operating cash"):
        targeted_prompts.extend([
            (
                "What does the context say about cash flow?",
                first_sentences(chunk, max_sentences=2),
            ),
            (
                "Explain the cash flow situation described in this context.",
                first_sentences(chunk, max_sentences=2),
            ),
        ])

    if has_keywords(chunk, "risk", "adversely", "uncertain", "litigation"):
        targeted_prompts.append(
            (
                "What risk or cautionary points appear in this context?",
                first_sentences(chunk, max_sentences=2),
            )
        )

    if has_keywords(chunk, "margin", "profit", "operating income", "ebit"):
        targeted_prompts.extend([
            (
                "What does the context say about margins or profitability?",
                first_sentences(chunk, max_sentences=2),
            ),
            (
                "Explain the profitability metrics in this context.",
                first_sentences(chunk, max_sentences=2),
            ),
        ])

    if company:
        targeted_prompts.append(
            (
                f"Describe {company}'s performance using only the provided context.",
                summary_answer,
            )
        )

    if has_numbers(chunk):
        targeted_prompts.append(
            (
                "Extract the main financial figures from this context and explain them briefly.",
                summary_answer,
            )
        )

    rng.shuffle(prompts)
    ordered_prompts = targeted_prompts + prompts
    seen_instructions: set[str] = set()
    for instruction, answer in ordered_prompts:
        if instruction in seen_instructions:
            continue
        seen_instructions.add(instruction)
        records.append(
            {
                "instruction": instruction,
                "context": chunk,
                "answer": answer,
                "text": format_example(instruction, answer, context=chunk),
            }
        )
        if len(records) >= 3:
            break
    return records


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build an instruction corpus for FinLLM.")
    parser.add_argument("--corpus", default="financial_training_corpus_clean.txt")
    parser.add_argument("--output-dir", default="data/instruction")
    parser.add_argument("--max-examples", type=int, default=50000)
    parser.add_argument("--chunk-chars", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=1337)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rng = random.Random(args.seed)
    corpus_path = Path(args.corpus)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    jsonl_path = output_dir / "finance_sft.jsonl"
    txt_path = output_dir / "finance_sft.txt"

    count = 0
    with jsonl_path.open("w", encoding="utf8") as jsonl, txt_path.open("w", encoding="utf8") as txt:
        for question, answer in CURATED_QA:
            text = format_example(question, answer)
            jsonl.write(json.dumps({"instruction": question, "answer": answer, "text": text}) + "\n")
            txt.write(text + "\n")
            count += 1

        with corpus_path.open("r", encoding="utf8", errors="ignore") as handle:
            for line in tqdm(handle, desc="building instruction examples", unit="lines"):
                if count >= args.max_examples:
                    break
                for raw_chunk in chunk_text(line, chunk_chars=args.chunk_chars, overlap=0):
                    chunk = clean_chunk(raw_chunk)
                    if chunk is None:
                        continue
                    for record in records_for_chunk(chunk, rng):
                        jsonl.write(json.dumps(record, ensure_ascii=True) + "\n")
                        txt.write(record["text"] + "\n")
                        count += 1
                        if count >= args.max_examples:
                            break
                    if count >= args.max_examples:
                        break

    print(json.dumps({"examples": count, "jsonl": str(jsonl_path), "text": str(txt_path)}, indent=2))


if __name__ == "__main__":
    main()
